/**
 * Cross-verify the Rust-side signing helper with the TS-side verifier.
 *
 * Fixture is generated by:
 *   cargo test --manifest-path vigil-agent/Cargo.toml -- \
 *     result_signing::tests::emit_ts_fixture --nocapture --ignored
 *
 * Ed25519 signatures are deterministic, so if canonical JSON output matches
 * on both sides, a Rust-produced signature must verify cleanly in TS.
 *
 * Run with: node vigil-hub/tests/signature-verify.test.mjs
 */

import assert from "node:assert/strict";
import { verifyEd25519, canonicalJson, canonicalBodyForSigning } from "../lib/signature-verify.ts";

// --- Fixture (from Rust emit_ts_fixture) ---------------------------------
const FIXTURE = {
  pubkey_hex:
    "8f1e574d1587e6b3a5216223d2de4a8f17bda346b91e01942c8b797654effae3",
  body: {
    type: "check_result",
    check_name: "service:Spooler",
    status: "ok",
    latency_ms: 12,
    metadata: { b: 2, a: 1 },
  },
  canonical:
    '{"check_name":"service:Spooler","latency_ms":12,"metadata":{"a":1,"b":2},"status":"ok","type":"check_result"}',
  signature_hex:
    "2270fd9b44a82822df24bfb87b4e61ce2341ed17cf350a500aac3b9208cc415434d97d0cce03589b726ef05042ff9f4829b727e6254484603dfa1ef682c9b100",
};

// 1. Canonical JSON on TS side matches Rust side byte-for-byte.
assert.equal(
  canonicalJson(FIXTURE.body),
  FIXTURE.canonical,
  "canonicalJson output does not match Rust fixture",
);

// 2. Signature verifies against the canonical bytes.
assert.equal(
  verifyEd25519(FIXTURE.pubkey_hex, FIXTURE.signature_hex, FIXTURE.canonical),
  true,
  "verifyEd25519 rejected Rust-generated signature",
);

// 3. Tampering the body invalidates the signature.
const tampered = { ...FIXTURE.body, status: "critical" };
assert.equal(
  verifyEd25519(
    FIXTURE.pubkey_hex,
    FIXTURE.signature_hex,
    canonicalJson(tampered),
  ),
  false,
  "tampered message should not verify",
);

// 4. canonicalBodyForSigning round-trip: inject + strip signature.
const withSig = { ...FIXTURE.body, signature: FIXTURE.signature_hex };
assert.equal(
  canonicalBodyForSigning(withSig),
  FIXTURE.canonical,
  "canonicalBodyForSigning did not strip signature cleanly",
);

console.log("OK - TS verifier accepts Rust-generated ed25519 signatures");
